version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mtb-stock-notification-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-f2thd3hd7rf3"
s3_prefix = "mtb-stock-notification-sam"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["MTBStockNotification=747340109238.dkr.ecr.ap-southeast-2.amazonaws.com/mtbstocknotification"]
