AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  SAM Template for mtb-stock-notification

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  MTBStockNotification:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      MemorySize: 384
      ImageUri: '747340109238.dkr.ecr.ap-southeast-2.amazonaws.com/mtbstocknotification'
      Events:
        MTBStockNotificationSchedule:
          Type: Schedule
          Properties:
            Schedule: 'rate(4 hours)'
            Name: mtb-stock-notification
            Enabled: True
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: mobile
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./source
      DockerTag: python3.8-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MTBStockNotification:
    Description: "MTBStockNotification Function ARN"
    Value: !GetAtt MTBStockNotification.Arn
  MTBStockNotificationIamRole:
    Description: "Implicit IAM Role created for MTBStockNotification function"
    Value: !GetAtt MTBStockNotificationRole.Arn
