AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  SAM Template for mtb-stock-notification

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 120

Resources:
  MTBStockNotification:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      MemorySize: 230
      ImageUri: 'mtbstocknotification'
      Events:
        MTBStockNotificationSchedule:
          Type: Schedule
          Properties:
            Schedule: 'rate(5 minutes)'
            Name: mtb-stock-notification
            Enabled: True
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: mobile
        - SNSPublishMessagePolicy:
            TopicName: personal-email
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./source
      DockerTag: python3.8-v1
      DockerBuildArgs: {"--platform": "linux/amd64"}

Outputs:
  MTBStockNotification:
    Description: "MTBStockNotification Function ARN"
    Value: !GetAtt MTBStockNotification.Arn
  MTBStockNotificationIamRole:
    Description: "Implicit IAM Role created for MTBStockNotification function"
    Value: !GetAtt MTBStockNotificationRole.Arn
